# Generated by Django 4.2.5 on 2023-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
